//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net.Web.Api.Sdk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Net.Web.Api.Sdk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is required..
        /// </summary>
        internal static string FieldRequiredText {
            get {
                return ResourceManager.GetString("FieldRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size {0} exceeds the authorized limit of {1}..
        /// </summary>
        internal static string FileSizeLimitReachedText {
            get {
                return ResourceManager.GetString("FileSizeLimitReachedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSD-2-Clause OR MIT.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field contains a media type &apos;{1}&apos; that is not allowed..
        /// </summary>
        internal static string MimeTypeNotAllowedText {
            get {
                return ResourceManager.GetString("MimeTypeNotAllowedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token name &apos;{0}&apos; was not found..
        /// </summary>
        internal static string TokenNameNotFound {
            get {
                return ResourceManager.GetString("TokenNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following token payload keys are duplicated: {0}..
        /// </summary>
        internal static string TokenPayloadDuplicatedKeys {
            get {
                return ResourceManager.GetString("TokenPayloadDuplicatedKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token payload keys are not allowed to be empty..
        /// </summary>
        internal static string TokenPayloadEmptyKeyNoAllowed {
            get {
                return ResourceManager.GetString("TokenPayloadEmptyKeyNoAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token payload values are not allowed to be empty..
        /// </summary>
        internal static string TokenPayloadEmptyValuesAreNotAllowed {
            get {
                return ResourceManager.GetString("TokenPayloadEmptyValuesAreNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following token payload keys are reserved: {0}..
        /// </summary>
        internal static string TokenPayloadReservedKeys {
            get {
                return ResourceManager.GetString("TokenPayloadReservedKeys", resourceCulture);
            }
        }
    }
}
